### PR TITLE
Add issue triage guidelines to CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by niveditc**
**Summary**

We've been loosely following these guidelines for the past month & they seem to be working well. Adding to `CONTRIBUTING.md` to make it more visible.

**Test Plan**
screenshot 2018-10-14 12 54 05

### CODE REVIEW

**Comment by juliankrispel** [comment]
That’s awesome!

It’d be great imo to clarify what kind of prs will be accepted. So the
community knows before they open one. Wdyt?

**Comment by juliankrispel** [comment]
Though that is a different issue altogether 😅

**Comment by claudiopro** [comment]
This is great for new contributors! Thanks for writing this up @niveditc.

I'd make an example for the last bullet point, e.g. **chrome**, **firefox**, **macos**, **android** and so forth. Note that **osx** should be renamed to **macos** to match the current name of the OS (I just renamed it).

**Comment by niveditc** [comment]
@claudiopro - thanks for the suggestion! I added in the examples :)

**Pull request closed without merging**
