### PR TITLE
change convertFromRaw to return a ContentState, fixes #230

### LINKED ISSUE #230: convertToRaw and convertFromRaw not quite parallel
Hey, first off let me just say thanks for the awesome library! Currently getting familiar with it, and implementing HTML parsing to be able to store content as HTML in the database, but use Draft as the editor. Love the concept of it.

I noticed that `convertToRaw` and `convertFromRaw` aren't quite parallel, and I was wondering why? `convertFromRaw` returns an array of `ContentBlock`s that you have to convert into a `ContentState` yourself, and `convertToRaw` takes a fully-formed `ContentState`.

It seems like it would be nicer for consistency if `convertFromRaw` returned a `ContentState` instead of an array of `ContentBlock`s. (Or vice versa if there's a reason for wanting the lower-level array of blocks.)

### PR DESCRIPTION
**Pull request by ianstormtaylor**
This way convertFromRaw and convertToRaw are parallel, both dealing with ContentState instead of one returning an array of ContentBlocks. Fixes #230.

@hellendag Let me know how this looks! I didn't see any tests for the converters, and I haven't used Flow before, or contributed to any Facebook repos.

### CODE REVIEW

**Comment by hellendag** [comment]
Yeah, I have some tests that I need to get into the OS repo. It's on my todo list. :) The change looks good, so I'll go ahead and import.

You can check flow by running `flow` in the `src` directory. #245 will also help with this.

**Comment by hellendag** [comment]
@facebook-github-bot import

**Comment by johanneslumpe** [comment]
@hellendag Since this is a breaking change, will you bump the version accordingly to 1.x?

**Comment by remko** [comment]
@johanneslumpe 0.x.y releases don't need major bumps on breaking changes (per [semver](http://semver.org/#spec-item-4)).

**Comment by johanneslumpe** [comment]
@remko true but it is still nice for users to not have their codebase break out of the blue with a new release.

**Comment by hellendag** [comment]
I'll probably keep it a 0.x.0 release, and just be sure to mark it as a breaking change in the changelog.


On Apr 17, 2016, at 04:12, Johannes Lumpe <notifications@github.com<mailto:notifications@github.com>> wrote:

@remko true but it is still nice for users to not have their codebase break out of the blue with a new release.

**Pull request closed without merging**
