### PR TITLE
add 'Prettier'

### LINKED ISSUE #1083: Use 'Prettier' on the Draft.js codebase
See https://github.com/prettier/prettier

### PR DESCRIPTION
**Pull request by hieven**
close #1083

### CODE REVIEW

**Comment by hieven** [comment]
@langpavel 
Oops, I forget to format current codebase before making this PR.
Thanks for the remind

After formating code, I cannot pass eslint :cold_sweat:
I have no idea how to fix this, do I need to change the rule of eslint?

**Comment by langpavel** [comment]
> do I need to change the rule of eslint?

Yes if they are in conflict with prettier

**Comment by flarnie** [comment]
Yea, this is probably a more significant undertaking than I had been thinking. I removed the 'good-first-bug' tag but it would still be great to have this done. I will try to add some details to the issue when I get a chance.

**Comment by hieven** [comment]
@flarnie 
ok! 
Let me know is there anything I can help when you have time :-)

**Comment by spicyj** [comment]
Going to close this for now since we haven't figured out what we want to do here yet.

**Pull request closed without merging**
