### PR TITLE
Allow to style editor nodes with CSS classes

### PR DESCRIPTION
**Pull request by andresgutgon**
# Summary
Until now you could pass an inline style CSS object for `BOLD` or `ITALIC`. With this new prop `customCssClassesMap` you can pass CSS classes. Which allow to use your own styles or utility classes like TailwindCSS

This `red` color is set with a TailwindCSS class
image

``` javascript
const customCssClassMap = {
  BOLD: 'text-red-600'
}
<Editor
  customCssClassMap={customCssClassMap}
  {...otherProps}
/>
```

## Related Issues and PR
https://github.com/facebook/draft-js/pull/2164
https://github.com/facebook/draft-js/issues/957

### CODE REVIEW

**Comment by andresgutgon** [comment]
I had to develop as [explained here](https://github.com/facebook/draft-js/issues/2864)

**Comment by andresgutgon** [comment]
The CI is broken due to that error : )

**Comment by andresgutgon** [comment]
Although looking into documentation not sure if we need this PR having this prop:
https://draftjs.org/docs/advanced-topics-block-styling/#blockstylefn

Thoughts?

**Comment by charuwts** [comment]
> Although looking into documentation not sure if we need this PR having this prop: https://draftjs.org/docs/advanced-topics-block-styling/#blockstylefn
> 
> Thoughts?

As far as I can tell that is only for block level styling. It would be a serious improvement to have them inline.

I do see a couple threads saying this won't be implemented: e.g. https://github.com/facebook/draft-js/issues/957 But there are a couple pull requests already so I don't see why it's been rejected...

**Comment by charuwts** [comment]
Does anyone know of a plugin that adds this ability?

**Comment by andresgutgon** [comment]
No longer working on this. Feel free to copy and re-open your own PR from here : )

**Pull request closed without merging**
