### PR TITLE
[WIP] Change `handle` functions to return enum instead of boolean #339

### PR DESCRIPTION
**Pull request by guitardave24**
cc @hellendag, just getting a quick gut check before I plunge into changing more handlers.

### CODE REVIEW

**Comment by hellendag** [comment]
Ah, you should coordinate with @johanneslumpe -- see #340.

I like the wrapper function for checking whether the event is handled.

**Comment by guitardave24** [comment]
Doh, should have looked. @johanneslumpe I'm happy to let you carry on with this and close mine.

**Comment by johanneslumpe** [comment]
@guitardave24 like @hellendag said, nice approach with the handler function. Do you mind me integrating that into my PR?

**Comment by guitardave24** [comment]
johanneslumpe Sounds good, once that's done I'll close out my PR.

**Comment by hellendag** [comment]
@johanneslumpe Sure, that works for me.

**Comment by johanneslumpe** [comment]
@guitardave24 It's in now :)

**Pull request closed without merging**
