### PR TITLE
allow for React 16 as peerDependency

### PR DESCRIPTION
**Pull request by nikgraf**
**Summary**

As Sophie suggested adding React 16 RC helps to avoid peerDep warnings. see https://twitter.com/sophiebits/status/906661088472813568

### CODE REVIEW

**Comment by ArnaudRinquin** [comment]
Appart from the `peerDependency` warning, have you spotted any issue with React 16?

**Comment by flarnie** [comment]
Thanks for adding this! 🎉🎊🍰

The tests ran successfully for me locally, so hopefully that failed CI test run was just a fluke. Restarted the tests, and assuming we can get those passing then I'll be happy to merge this.

**Comment by nikgraf** [comment]
yay 🎉

**Comment by flarnie** [comment]
Hmm - I still don't get those test failures. It looks like you rebased, but I might try rebasing again because those failures are almost certainly not related to the React dependency bump.

**Comment by flarnie** [comment]
Tests continue to pass for me locally, even after `git checkout master && git rebase upstream/master && yarn install && yarn upgrade && yarn build`. 🤷‍♀️

**Comment by nikgraf** [comment]
@flarnie weird, especially since it complains `SyntaxError: Unexpected token )` while I didn't change anything: https://travis-ci.org/facebook/draft-js/jobs/278594841

also the same changes with master merged into the branch went flawlessly, see: https://travis-ci.org/facebook/draft-js/builds/278655176

**Comment by flarnie** [comment]
Internally I keep getting the message "This seems to be a transient issue. Retry your job, and it will likely pass ." but retrying does not help... Maybe it will be fixed on Monday.

**Comment by JLarky** [comment]
I still get warning
```
npm WARN enzyme@2.9.1 requires a peer of react@0.13.x || 0.14.x || ^15.0.0-0 || 15.x but none was installed.
```

I think it means that you need to update package.json from
```
    "enzyme": "^2.9.1",
```
to
```
    "enzyme": "^3.0.0",
```

**Comment by flarnie** [comment]
I think even better would be to move `enzyme` from `dependencies` to `devDependencies`, because I'm certain we don't need it for anything Draft does in Production. Sorry about that!

Would you like to submit a PR? Or I can do it sometime tomorrow.

**Comment by JLarky** [comment]
@flarnie I'm ok with someone else doing this :) it seems like this is just a warning and it still work for now :)

**Pull request closed without merging**
