### PR TITLE
Bug/1668

### PR DESCRIPTION
**Pull request by bambii7**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure that:
  * The test suite passes (`npm test`)
  * Your code lints (`npm run lint`) and passes Flow (`npm run flow`)
  * You have followed the [testing guidelines](https://github.com/facebook/draft-js/wiki/Testing-for-Pull-Requests)
5. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

Please use the simple form below as a guideline for describing your pull request.

Thanks for contributing to Draft.js!

-

**Summary**

Updating examples package.json to reference parent projects react & react dom versions. This ensures its kept in sync with the Draftjs version. 

**Test Plan**

This commit updates example package.json. Not sure it is testable with jest. Unless its possible to detect when two versions of react are loaded.

### CODE REVIEW

**Comment by niveditc** [comment]
@bambii7 - thank you for submitting this PR. Could you please rebase on master? Then I can merge this in.

**Comment by niveditc** [comment]
Uh, now there are 105 commits here. You should submit only the commits that are specific to this PR.

Feel free to open a new PR with your changes if rebasing on master & resolving the merge conflicts is proving challenging!

**Comment by bambii7** [comment]
Sorry @niveditc I rebased then pulled, think I needed to rebase then force push to keep HEAD in sync with upstream master. I'll see if I can correct.

**Comment by bambii7** [comment]
@niveditc has this fixed the issue? I'm still a little fresh at submitting pull requests through a fork.

**Comment by niveditc** [comment]
@bambii7 - awesome! One last thing - could you update the summary & test plan above? :)

**Comment by bambii7** [comment]
@niveditc done, thank you for your patience :) I'm better equiped to deal with more issues now.

**Pull request closed without merging**
