### PR TITLE
Fix react-unknown-prop warning in the tweet example

### PR DESCRIPTION
**Pull request by wuct**
I am playing with the tweet example and find there is a [unknown-prop-warning](https://facebook.github.io/react/warnings/unknown-prop.html). I fix the warning by this PR.

### CODE REVIEW

**Comment by facebook-github-bot-0** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-2** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by stopachka** [comment]
cc @hellendag - I remember having an issue with decorators, when they did not have a `data-offset-key` -- do we want to show that in this example?

**Comment by wuct** [comment]
Sure, `data-offset-key`s are added by https://github.com/facebook/draft-js/pull/620/commits/1553851ab7470abf1f5d8771771dfbede92cd4b1.

**Comment by flarnie** [comment]
The Travis error looks unrelated to this change, and will probably be fixed by rebasing onto master.

The fix makes sense - I'm just wondering why this doesn't match the documentation. Either something changed, or the documentation was wrong from the start. I'd like to look into this more before merging.

Thanks for submitting this @wuct - I'll get back to it in the next couple of days. In the mean time, it would be good to rebase this and get the build passing.

@stopachka @hellendag Can you explain what `data-offset-key` is used for? Should we add that to [the documentation](https://facebook.github.io/draft-js/docs/advanced-topics-decorators.html#content)?

**Comment by wuct** [comment]
@flarnie I have rebased it but the build still failed.

**Comment by flarnie** [comment]
I've looked into it a bit, and we should update the documentation to reflect this new example. Opening [a separate issue](https://github.com/facebook/draft-js/issues/701) for that though.

**Comment by FanXiang** [comment]
When i testing the tweet example, **Error：** ``contentBlock.getText is not a function``.

**Pull request merged**
