### PR TITLE
Migrated from using 'createClass' per issue 1160

### PR DESCRIPTION
**Pull request by morrme**
**Summary**
Fixes: #1160
Replaced usage of createClass with createReactClass.

### CODE REVIEW

**Comment by morrme** [comment]
@flarnie Seems like one test on Travis failed, saying to "arc build"? Please advise.

**Comment by mmmoussa** [comment]
I think you need to update the version of React being required in `package.json`.

**Comment by morrme** [comment]
@mmmoussa I tried that and have gotten the same result.

**Comment by jomasti** [comment]
`website/package.json` is missing the dependency.

**Comment by morrme** [comment]
@jomasti thanks for the suggestion. it is still failing :(   it definitely seems related to the versions, so i need to see if react-dom has a more recent version now, i think

**Comment by flarnie** [comment]
Thanks for working on this! I'll take a look in a bit and see if we can get CI passing.

**Comment by flarnie** [comment]
I checked this out, rebased it onto master, and was able to build the website with no issue. I'm hoping that whatever problem was happening in CI is solved by rebasing.

**Comment by flarnie** [comment]
We are thinking the issue is an incompatibility between the new React build system and the unmaintained `react-page-middleware` which we use for the Draft.js docs site. https://github.com/facebookarchive/react-page-middleware

Probably should migrate off of `react-page-middleware` but for now we'll just stick with an earlier version of React.

**Comment by niveditc** [comment]
These files were deleted when we migrated the website to Docusaurus in #1759 so this is no longer needed.

**Pull request closed without merging**
