### PR TITLE
Update Overview.md

### PR DESCRIPTION
**Pull request by oscarmorrison**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure that:
  * The test suite passes (`npm test`)
  * Your code lints (`npm run lint`) and passes Flow (`npm run flow`)
  * You have followed the [testing guidelines](https://github.com/facebook/draft-js/wiki/Testing-for-Pull-Requests)
5. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

Please use the simple form below as a guideline for describing your pull request.

Thanks for contributing to Draft.js!

-

**Summary**
Remove unneeded code in example 
[...]

**Test Plan**
No functional change
[...]

Simplifies code and minimizes new concepts.

### CODE REVIEW

**Comment by oscarmorrison** [comment]
@davidchang @hellendag 👀

**Comment by flarnie** [comment]
Hi @oscarmorrison! We appreciate your attention to the documentation and helping us improve. I believe that the proposed change would put that line over 80 characters, which is the limit we usually use for line length within Facebook. I assume that is why the variable assignment was there.

In fact - if you're looking for quick wins to improve this project, fixing long lines in the Draft.js source and docs would be helpful. There are many lines over 80 characters throughout the Draft.js source. We're looking to enable better linting of this, but for now I don't think our linter is flagging it.

**Comment by oscarmorrison** [comment]
Hi @flarnie thanks for the comment. 
The line is now exactly 80 characters. 

I was actually doing it as I was ramping someone up on Draft who was also new to React (& ES6) 
and they found the destructuring confusing.

Also as you can see in the example code on the next page in the docs:
https://facebook.github.io/draft-js/docs/quickstart-api-basics.html#content
`return <input value={this.state.value} onChange={this.onChange} />;`

is there. so it keeps the consistency

**Comment by flarnie** [comment]
@oscarmorrison You have a good point about the destructuring potentially being confusing for folks who are new to ES6/JS/React, and the new syntax is also more consistent with the other example.

The line is exactly 80 characters when we don't take the indentation into account. With the indentation it crosses the 80 character line, shown in red in my editor here:
screen shot 2016-12-10 at 4 53 33 pm

In cases like this we usually use parenthesis to wrap to the next line:
screen shot 2016-12-10 at 4 57 10 pm

I'd be happy to land this if it were tweaked in this way, and thanks for explaining. I should have made this suggestion in the first place rather than closing the PR, sorry about that.

**Comment by oscarmorrison** [comment]
Done. Thanks for reopening.

**Comment by oscarmorrison** [comment]
Also it seems that your linter max len is 120:
https://github.com/facebook/fbjs/blob/master/packages/eslint-config-fbjs/index.js#L310

**Comment by oscarmorrison** [comment]
Fixed a spacing typo and rebased. All good to go. Thanks @flarnie

**Comment by flarnie** [comment]
Thanks for flagging that the linter is still set to 120. Internally we just moved to 80 fairly recently, I need to get the linter here in sync with our internal one. And thanks for updating this!

**Pull request merged**
