### PR TITLE
Adds BLM banner

### PR DESCRIPTION
**Pull request by claudiopro**
**Summary**

Adds a Black Lives Matter banner like other OSS projects of the React family

**Test Plan**

Local tests

```
cd website
yarn 
yarn start
```

## Screenshots
Screen Shot 2020-06-02 at 21 10 00

Screen Shot 2020-06-02 at 21 09 18

Screen Shot 2020-06-02 at 21 10 07

### CODE REVIEW

**Comment by claudiopro** [comment]
@yangshun I have no idea how to add a banner above the navbar. Is this possible with a declarative config like the one we have here in ?

**Comment by claudiopro** [comment]
Thank you @kedromelon!

**Comment by yangshun** [comment]
@claudiopro you can use the [announcement bar feature](https://v2.docusaurus.io/docs/theme-classic/#announcement-bar).

An example PR - https://github.com/facebookexperimental/Recoil/pull/241

**Comment by claudiopro** [comment]
Thank you @yangshun, I'll look into this today!

**Comment by RAYDENFilipp** [comment]
Because of this change, the site became inaccessible

What happened to links
image

It is hard to see links.

**Pull request closed without merging**
