### PR TITLE
Fix typing Chinese in Edge (#2082)

### LINKED ISSUE #2082: Cannot type Chinese in Edge
To reproduce:

* Use the latest version of Draft (i.e., one that includes https://github.com/facebook/draft-js/commit/634bd297f1646934087051b1149164b01a09a136)
* In Microsoft Edge, open the rich text example
* Switch to Chinese, with the standard Microsoft IME.
* Type `nihao1`

Result: the text disappears. See the below screencast:

screencast 2019-05-22 17-24-08

Note that it does work correctly when the block already contains some text.

### PR DESCRIPTION
**Pull request by robbertbrak**
Fixes #2082.

### CODE REVIEW

**Comment by fabiomcosta** [comment]
LGTM

**Comment by fabiomcosta** [comment]
cc @claudiopro or anyone that could merge this :/
The travis error doesn't look related to this PR

**Comment by atsuoishimoto** [comment]
I confirmed this patch fixes Japanese issue.

**Comment by mrkev** [comment]
Huh, how did this fall off the radar.

Let me see what's up.

**Pull request closed without merging**
