### PR TITLE
Add aria-multiline attr to DraftEditor

### PR DESCRIPTION
**Pull request by jessebeach**
`aria-multiline` is used to indicate to assistive technology agents that a textbox is a multiline textbox. When `aria-multiline` is true, an AT should treat return key presses as carriage returns, not submit actions.

https://www.w3.org/TR/wai-aria-1.1/#aria-multiline

teeeeeeeested: `npm run test && npm run lint && npm run flow`

### CODE REVIEW

**Comment by spicyj** [comment]
Cool! Do screen readers support this property yet?

**Comment by jessebeach** [comment]
@spicyj no, not yet. @mcking65 is working with them as part of the ARIA 1.1 specification process. 

https://codepen.io/jessebeach/pen/gRVKeY

**Comment by flarnie** [comment]
I'm excited to land this, the build keeps failing. Going to try a couple more times, I'm not getting much info on why it failed.

**Comment by jessebeach** [comment]
💯 💯 💯 💯 💯 💯

**Comment by flarnie** [comment]
@jessebeach can you try making this an internal diff and then we can export it to github? I don't know why the build won't pass when I import it from github.

cc @zpao

**Comment by jessebeach** [comment]
Will do.

**Comment by spicyj** [comment]
@flarnie See the error here if you click through the internal build logs: https://fburl.com/hhnvslws. I think maybe removing the "tested:" section would help?

**Comment by jessebeach** [comment]
It might be failing because a Jest snapshot needed to be updated.

**Comment by flarnie** [comment]
Thanks @spicyj - that was the issue.

**Pull request closed without merging**
