### PR TITLE
Expose html to block converter through Draft object

### PR DESCRIPTION
**Pull request by CLowbrow**
Optional second parameter to pass in a function that will generate a dom element from whichever implementation. 

Should help with #55

### CODE REVIEW

**Comment by CLowbrow** [comment]
@facebook-github-bot import

(please bear with me as I flail around getting this to work)

**Comment by AlastairTaft** [comment]
This seems pretty useful. I've just hit the point where I'd like to hydrate the editor from some markdown content. To get up and running quickly, I'm converting from markdown to html and now would like to populate my editor with html.

**Comment by CLowbrow** [comment]
@facebook-github-bot import

**Comment by remko** [comment]
Will there be a way to hook into converting unknown block elements (eg `figurè, `img`)? Would be useful for custom blocks.

**Comment by CLowbrow** [comment]
@remko There is a conversation about that in https://github.com/facebook/draft-js/issues/166 

I haven't written anything yet so feedback on what kind of API you would like would be appreciated.

**Comment by CLowbrow** [comment]
@remko oh boy you opened that I am sorry. D: D: D:

**Pull request closed without merging**
