### PR TITLE
removes iOS format tooltips everywhere

### LINKED ISSUE #214: iOS format tooltip button deletes text
Hi,
when I select text in the demo, besides the usual copy, cut etc. options I can also select a text-format (**B** _I_ U) button:
img_4239
So when I use these functions to format the text, the selected text or the text before the selection is deleted. Also the draft-js editor buttons (e.g. bold or italic) won't get highlighted.

As long as this bug is present does anybody know how I can hide this button?

### PR DESCRIPTION
**Pull request by SecurityInsanity**
fixes #214

thanks to @bradleyayers excellent digging it turns out there's a
CSS property you can assign to disable the bold/italics/underline
for iOS. although you can techincally apply this style seperately
, since the editor breaks due to the unexpected dom mutations i
think it's best if this actually gets defaultly added to the root
of the editor. which this commit does.

### CODE REVIEW

**Comment by facebook-github-bot-5** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-1** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by LucidityDesign** [comment]
When I add these css properties to the draft root element, I get the problem that the placeholder won't disappear as I start typing. I had to add the css to `.public-DraftEditor-content` to solve that problem

**Comment by SecurityInsanity** [comment]
Hmmm, good catch with the placeholder. I'll change that.

**Comment by hellendag** [comment]
This is fantastic. Thanks @SecurityInsanity and @bradleyayers!

**Comment by LucidityDesign** [comment]
I also get problems when setting the editor to read only. With `user-modify` I still can edit text

**Pull request merged**
