### PR TITLE
jest@23.0.0

### PR DESCRIPTION
**Pull request by aaronabramov**
update jest to the latest version

### CODE REVIEW

**Comment by niveditc** [comment]
@aaronabramov, @NoamELB - you'll need to rebase on master (especially past https://github.com/facebook/draft-js/commit/e2c24cf8c5ef0d752bca962b5859810b02a4568b). Let me know if you'd like me to update this if it's more convenient (and is 23.0.0 still the latest version)?

**Comment by aaronabramov** [comment]
hey! didn't realize it was still open. i got stuck rebasing this diff in phabricator and wasn't sure what the correct process for it was. since it's just a one line change i'll just close this (and this is not the latest version any more).

**Comment by niveditc** [comment]
@aaronabramov - I can make the change since it would be good to update to the latest version (whatever www is using). Could you tell me what that version is? :)

**Comment by aaronabramov** [comment]
@niveditc you can just do `yarn add jest@latest`

**Pull request closed without merging**
