### PR TITLE
Add Slack signup info to readme

### PR DESCRIPTION
**Pull request by hellendag**

### CODE REVIEW

**Comment by hellendag** [comment]
@facebook-github-bot shipit

**Comment by zpao** [comment]
Thoughts on just using a #draftjs channel in the reactiflux discord?

**Comment by spicyj** [comment]
There's also this project which auto-sends Slack invites: http://rauchg.com/slackin/.

**Comment by hellendag** [comment]
Using the reactiflux Discord sounds like a good move. I'll stick with this until I can figure out how to do that.

**Pull request closed without merging**
