### PR TITLE
add pasteUniqueEntities prop to DraftEditor

### PR DESCRIPTION
**Pull request by afraser**
**Summary**

Fixes: https://github.com/facebook/draft-js/issues/504 and https://github.com/facebook/draft-js/issues/390

I'd love to get some feedback on what I can do to get this accepted.

Some use cases for this:
- equations (implemented here)
- chemical diagrams
- sparklines
- cloze sentences (i.e. fill in the blanks) where the blanks have potential correct solutions
- contextual notes ala google docs

TODO:
- [ ] Distill the equation example.

**Test Plan**
- [x] ensure entities are not cloned when `pasteUniqueEntities={false}`
- [x] ensure entities are cloned when `pasteUniqueEntities={true}`
- [x] ensure entity references are pasted in the right place
- [ ] ensure that pasting plain text (non-internal paste) works as expected
- [ ] ensure that pasting plain HTML (non-internal paste) works as expected

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-5** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by afraser** [comment]
Another solution I think I might try instead of the `draftEntityKeyPrefix` solution is to leave it up to the user to implement the entity decorator such that it renders the editorKey on the DOM somewhere if they want `pasteUniqueEntitiies` for entities that are rendered with content that isn't the same as what's in the plain text. This way there's no need for this `else`: https://github.com/facebook/draft-js/pull/525/files#diff-3e4f7f7129a394d16c3592dd894fd31eR135

**Comment by afraser** [comment]
Update: I now use `editorKey` instead of `draftEntityPrefix` to detect internal pasting of entities in selections that are within a block. This requires the user to include the editorKey somewhere in the markup of their component.

**Comment by ericbiewener** [comment]
The example doesn't work well for me. If I move the carat with my arrow keys, as soon as I reach the equation it jumps back to the beginning.

**Comment by flarnie** [comment]
Hi - first of all, sorry that this PR got stale with no review. Looking at it not, I would be open to merging something similar but with a different approach.

Rather than adding a prop, should we just change the default behavior here? When would you ever want a copy-pasted section to refer to the same entities as in the original section?

I would need to verify that none of Facebook's use cases rely on the current behavior, but I doubt they do.

So for now closing this PR but if @afraser or others are still interested in fixing this please open a new issue/PR.  Thanks!

**Comment by afraser** [comment]
@flarnie Thanks for getting back to me on this. I've long since moved on from the project in question, but I totally get what you're saying about changing the approach.

**Pull request closed without merging**
