### PR TITLE
Fix React children mutation warning

### LINKED ISSUE #590: Component's children should not be mutated- draft-js@0.7 react@15.3.0
when try to toggle blockType to ordered-list-item, unordered-list-item, code-block. getting error :

VM16882 bundle.js:1302 Warning: Component's children should not be mutated.
    in pre
    in div (created by DraftEditorContents)
    in DraftEditorContents (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in div (created by DraftEditor)
    in DraftEditor (created by PluginEditor)
    in PluginEditor (created by KeyPathEditor)
    in div (created by KeyPathEditor)

it occurred for all those block that have wrapper element..

it caused by mutation checking  
`if (element._shadowChildren.length === element.props.children.length) `

### PR DESCRIPTION
**Pull request by spicyj**
Fixes #590.

Test Plan:
screenshot of some nested lists in draft

### CODE REVIEW

**Comment by flarnie** [comment]
Logic lgtm and I was able to sort of manually test by pasting in a nested list. If there is a default keyboard shortcut to make nested lists I'm wondering what it is - didn't see one in `getDefaultKeyBinding.js`

---

screen shot 2016-09-05 at 9 53 10 am

**Comment by spicyj** [comment]
No, see #611 for where I add it to the example.

**Comment by flarnie** [comment]
Ah - I missed the dependency. I'll merge that one too then - thanks!

**Comment by spicyj** [comment]
No worries! This one is correct with that change too; it's just harder to test in the example (as you found).

**Pull request merged**
