### PR TITLE
Minor fixes

### PR DESCRIPTION
**Pull request by ronbak**
Hi,

this merge request fixes some minor issues.
It was created with help of [Feram][repo].

If it helped to improve this repository,
please consider to [star Feram's repo][repo] to show some love! 😊

PS:
The [Feram team][feramhq] is currently working on making this technology
available for everyone. If you want to be one of the first to use it,
please sign up up for the newsletter on [feram.co].

[repo]: https://github.com/feramhq/feram
[feramhq]: https://github.com/feramhq
[feram.co]: http://feram.co

### CODE REVIEW

**Comment by facebook-github-bot-9** [comment]
Thank you for your pull request and welcome to our community. We require contributors to sign our Contributor License Agreement, and we don't seem to have you on file. In order for us to review and merge your code, please sign up at https://code.facebook.com/cla - and if you have received this in error or have any questions, please drop us a line at cla@fb.com. Thanks!

**Comment by facebook-github-bot-7** [comment]
Thank you for signing our Contributor License Agreement. We can now accept your code for this (and any) Facebook open source project. Thanks!

**Comment by stopachka** [comment]
Nice! :)

**Comment by ronbak** [comment]
Thanks 😊 …but why don't you merge it then? 😯

**Comment by stopachka** [comment]
😊 oops!

**Pull request merged**
