### PR TITLE
Update flow and eslint-plugin-react, fix lints

### PR DESCRIPTION
**Pull request by flarnie**
**what is the change?:**
CI was failing because our version of flow was out of date, and changes
pulled from within FB had added lints and inconsistencies.

**why make this change?:**
To get CI passing so it will provide signal for PRs.

**test plan:**
`yarn test && yarn lint && flow src`

**issue:**
None, but flagged in PR https://github.com/facebook/draft-js/pull/1346

### CODE REVIEW

**Comment by flarnie** [comment]
tagging @aadsm for review if you are interested

also @spicyj

**Comment by aadsm** [comment]
This LGTM, I don't I have permission to approve though (write access is required).

**Comment by spicyj** [comment]
Add yourself here: https://fburl.com/xnny05ik.

**Comment by flarnie** [comment]
Opened a PR with `eslint-plugin-relay` to address one of the issues we have run into. https://github.com/relayjs/eslint-plugin-relay/pull/10

**Comment by flarnie** [comment]
Once this PR lands we can update `eslint-config-fbjs` and `eslint-plugin-relay` and re-add support for node 4.x in development. https://github.com/facebook/fbjs/pull/266

**Comment by flarnie** [comment]
please

**Pull request closed without merging**
