### PR TITLE
Facebook#1077 - Fix for input bug on Android - space or a special char clears the input

### PR DESCRIPTION
**Pull request by ashevtcov**
**Summary**

Fix for input bug on Android - typing space or a special char clears the input
https://github.com/facebook/draft-js/issues/1077

**Test Plan**
1. Add the component to your React website (test website)
2. Run Android emulator
3. Open your test website
4. Type a word into the component (for example, "All") and push space
5. Type another word (for example, "right") and push space

Expected behavior:
Text is not cleared, autocomplete is applied as expected

Wrong behavior fixed by this change:
Text is cleared or wrong symbols are added

### CODE REVIEW

**Comment by bchmn** [comment]
+1

**Comment by alandardic** [comment]
+1

**Comment by dorraba** [comment]
+1

**Comment by shaulgo** [comment]
+1

**Comment by gilatwix** [comment]
+1

**Comment by mxstbr** [comment]
This works perfectly in our project and fixes typing on my german Android keyboard.

**Comment by mxstbr** [comment]
Just to report back, we've been running this patch in production for a week now and have gotten 0 complaints about typing on Android anymore. :tada:

**Comment by rameshvishnoi90904** [comment]
is this committed ?

**Comment by mxstbr** [comment]
Update: This doesn't work perfectly, while it makes it possible to type on a german keyboard there's still bugs when autocorrecting/in some other cases that I haven't been able to track down. At least it doesn't crash the editor though...

**Comment by enterline** [comment]
+1

**Comment by arypurnomoz** [comment]
I found this works better with my keyboard

```
var composedChars = textInputData.trim() ? textInputData : compositionInputData + textInputData
```

due sometimes the value of `textInputData`  is `" "` (a space character)

**Comment by chenzhong13** [comment]
when input the first word, still exist this issue, but the next words are ok

**Comment by eriksape** [comment]
+1

**Comment by entregrammer** [comment]
+1

**Comment by inifaisal** [comment]
+1

**Comment by dfeinzeig** [comment]
ETA on this?

**Comment by mikesheetal** [comment]
+1

**Comment by ayyazdaniaryan** [comment]
Seeing this issue recently on draft-js using Gboard only.

**Comment by jonescr3** [comment]
+1

**Comment by jrserani** [comment]
Also confirmed that this is popping up on draft-js using Gboard.

**Comment by Slapbox** [comment]
Just tested this on Android and it 100% does not work. Unlike other editors, you can't even trick Draft into working.

**Comment by aminland** [comment]
This seems to be broken when the caret is placed in the middle of another word. Typing any character causes the full gboard suggestion to be inserted.

**Comment by Slapbox** [comment]
@aminland I can't get anywhere close to that level of functionality with Gboard.

**Comment by aminland** [comment]
Sorry I meant that's the behaviour with this PR applied.

**Comment by fabiomcosta** [comment]
@flarnie any way we could get this test and merged for any future release?
As you can see from the comments it's not the perfect fix, but at least people can type something when on `Gboard`. Currently it's completely broken.
I understand you might be very busy, we just want to know if this will be considered for a future version or not.
Thx for keeping this project going!

**Comment by pb-expa** [comment]
Bump.

**Comment by charlespeach** [comment]
bump! keen to know if this stop gap fix will be introduced

**Comment by sophiebits** [comment]
Am I correct in understanding that on these Android phones, no beforeinput events are received?

Does anyone know in what cases both data variables end up with nonempty content?

@arypurnomoz Can you elaborate on when you were seeing a space char in data where you wouldn’t expect?

If we can answer these three questions I think this PR should be OK for merge.

**Comment by mxstbr** [comment]
@sophiebits just to note, as I said above the typing experience still sucks on Android with this patch applied. Autocorrect messes the text up really really bad.

The only thing this patch adds is that the editor doesn't crash on Android, but imo this isn't anywhere ready for production usage with real users.

**Comment by mxstbr** [comment]
@pb-expa that's exactly what we did too! 👍  See https://github.com/withspectrum/spectrum/pull/2868, specifically our custom `draft-js-plugins-editor` wrapper:

https://github.com/withspectrum/spectrum/blob/e7d02da6d03348a54cbbb9c132512a9d8b477657/src/components/draft-js-plugins-editor/index.js#L80-L86

**Comment by ducnvhn** [comment]
+1

**Comment by tanat** [comment]
+1

**Comment by sophiebits** [comment]
## Please stop posting +1. I'm going to delete all the (many) +1 comments here. The way this gets merged is if we find answers to the questions I posted above.

**Comment by Slapbox** [comment]
Lots of information related to those questions here: https://github.com/ianstormtaylor/slate/issues/2062

As per @thesunny's research, as I understand it, there is no `beforeinput` before Android API 27, which corresponds with Android Oreo 8.1.0.

**Comment by sandorvasas** [comment]
@sophiebits You should just merge it, even a partial fix is a better fix than leaving it bugging. We heavily invested in integrating this component and turns out it's unusable on Android devices. It's a bad that it's not working, but it's real shame FB that you're even halting the patches to be merged.

**Comment by niveditc** [comment]
@thesunny - thanks so much for the detailed response above! I'm sure it will help inform further attempts for improving Android Web support in Draft.js.

I also wanted to mention that @flarnie has compiled a very thorough list of issues + explanation of the state of Android Web support on #1895 .

**Comment by ashevtcov** [comment]
Ok, my friends, I am closing this PR. First, it was never a fix for the full problem, I covered only limited number of issues, listed in the description - at that point in time it was enough. Since I issued this fix, Google implemented a lot of changes that make this fix just utterly insufficient: so many other issues appeared and fixing just this side effect doesn't change the game significantly at all.

**Pull request closed without merging**
