### PR TITLE
Upgrade immutable to v4 and flow to v0.57.2

### LINKED ISSUE #1425: Immutable-js newest version -> draft-js incompatible
### What happened

I updated to 4.0.0-rc.7.
Suddenly i noticed draft-js stopped working. Threw  an unrecoverable error.

### How to reproduce

Install draft-js 10.3, install the version of immutable i mentioned. It will happen naturally.

### PR DESCRIPTION
**Pull request by acusti**
**Summary**

Fixes #1425. 

**Test Plan**

All tests are passing. I think the editor could also use manual regression tests focusing on potential corner cases or scenarios that aren’t covered by the automated tests, though I don’t know what those would be.

### CODE REVIEW

**Comment by mitermayer** [comment]
I suggest we revisit this PR once immutable 4 is released. We could however split the flow version bump to a separate PR.

**Comment by Trafiz** [comment]
Is something happening with this PR? The warning in console: "Iterable.length has been deprecated, use iterable.size or iterable.count()" on the currently implemented version of immutable still occurs, so it will be good to update that library.

**Comment by niveditc** [comment]
I'm closing this PR since it doesn't work + flow has already been updated, but we should still try to fix #1425 (update immutable) to fix those issues.

**Comment by acusti** [comment]
@niveditc We’ve been using a built version of draft-js from this branch (merged with my iframe-compatible PR) in production for over a year now, so at least by some sort of definition, it definitely “works”. It’s also over a year out of date from latest draft-js `master`, and if Flow was already updated, I’m sure there are conflicts. What do you mean by “it doesn’t work”?

**Comment by niveditc** [comment]
@acusti - I think my wording was off - apologies for that! I meant that this PR as it stands today will probably be very difficult to rebase on master so it probably makes sense to deal with the immutable upgrade separately. There also seemed to be a suggestion that upgrading to immutable 4 is a better idea, though I think 3.8.1 is fine as an intermediate step if it fixes the issues described in #950 and #1647. Please feel free to open a new PR for this :)

**Comment by acusti** [comment]
@niveditc That makes sense! Thanks for the clarification. I’ll take a crack at remaking the changes in this PR against latest `master`.

**Comment by acusti** [comment]
i re-made the changes for immutable.sj v4 compatibility from scratch based off of latest `master`. those changes are in two PRs (one prep, one with the actual upgrade): #2955 and #2956

**Pull request closed without merging**
