### PR TITLE
Updates CHANGELOG for v0.11.0

### PR DESCRIPTION
**Pull request by claudiopro**
**Summary**

Updates the CHANGELOG for v0.11.0

This is going to be a refinement process from a very raw git log containing 200+ commits since v0.10.5. The focus should be on
- Advertising new functionality
- Highlighting breaking API changes
- Rolling up subsequent updates affecting the same feature or dependency into the most recent change to reduce the noise
- Attribute changes to contributors and link to relevant issues, PRs, and profiles

**Test Plan**

Proofreading

### CODE REVIEW

**Comment by fabiomcosta** [comment]
This is so exciting! I can't wait

**Comment by fabiomcosta** [comment]
For when is this new version planned?

**Comment by ddelrio1986** [comment]
As far as I know, I have not seen any plans to release v0.11.0.

**Comment by vladshcherbin** [comment]
@fabiomcosta @ddelrio1986 [mid april](https://github.com/facebook/draft-js/issues/2010#issuecomment-479670326) 🤔

**Comment by jdrzejb** [comment]
@claudiopro Are there any updates on planned release date? Do you need any help with some of the issues or PRs to speed things up?

**Comment by claudiopro** [comment]
Hi @fabiomcosta @jdrzejb thanks for checking! We missed the initial target date for 0.11 because of issues with internal customers at FB. There are currently no blocking issues on the OSS repo.

The plan to ship in mid April was quite optimistic, as I underestimated the time it took internal customers at FB to upgrade to the refactored HTML converter. Now that the effort to ship the new FB5 UI is subsiding, I expect the other maintainers to have more cycles to help out 🙏

**Comment by mrkev** [comment]
👀https://www.npmjs.com/package/draft-js/v/0.11.0

**Pull request closed without merging**
