### PR TITLE
Support rendering Draft-js into iframe

### PR DESCRIPTION
**Pull request by haikyuu**
**Summary**
This pull request adds support for draft-js usage inside iframes. There is another WIP PR  which tries to achieve the same thing #765. 

Note that this was mainly broken because `instanceof` does not check objects across iframes.
In other words (code) `iframeElement instanceof Element === false` while `iframeElement instanceof iframeDocument.Element === true`.

And the other reason is `getSelection` depends on the window object as well.

## Checking if a node is instance of `Element`, `HTMLElement` ...

Depending on the context, we need a way to access the right iframe window object to check using `instanceof`.

| ﻿Solutions                                                                             | D | Pros  👍                                                                 | Cons 👎                                                                                                                         | Shortcomings                                                                                |
|---------------------------------------------------------------------------------------|---|-----------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------|
| attach the iframeWindow to global object, and use it to check whenever it's available | 🛑 | - Easy access to iframe document                                            | - breaks when there is an instance of Draft-js inside the iframe and another outside.- breaks when there are +2 iframes as well |                                                                                             |
| get the document from the node itself and check                                       | ✅ | - Works fine even when there are many iframes or editors in and out iframes |                                                                                                                                 | - you can only access the global document when you have access to a node. (not needed here) |
| check the `nodeType`  property instead (used in [acusti's PR ](https://github.com/facebook/draft-js/pull/765))                         | 🛑 |                                                                             | - can't differentiate between Element and HTMLElement                                                                           |                                                                                             |

### Challenges

- When pasting something from a different context. We get a body element which document object doesn't have a corresponding  `window` / `defaultView` . It was fixed by adding another check.

## Accessing the window or document object in other cases `getSelection` ...
Whenever the `event` is accessible, we use it to access the `ownerDocument`

## Places skipped (they use the document and global objects)

- `getSafeBodyFromHTML` : it creates a new document anyway
- `getTextContentFromFiles` : it uses the `global.fileReader`

## Other challenges
In order to fix some flow errors, i had to force casting node types in some places. Note that i only did this after `instanceof` checks, so it's  safe. Those checks were not detected by flow because we use `instanceof` to check in iframe window or in the main window. One solution to fix this all together is to check nodes using a utility like [`fbjs`' `isNode` ](https://github.com/facebook/fbjs/blob/master/packages/fbjs/src/core/dom/isNode.js) but i prefer to keep the changes minimal.

## Known issues
- Inside an editor **in an iframe**: selecting some text and hitting `cmd+b` would apply the inline style but the selection will collapse. It happens only once, and **doesn't happen** outside an iframe. You can check it here and reproduce it in the [sandbox](https://codesandbox.io/s/y0q1q281kz)
draft-js-gif

**Test Plan**

I created [a sandbox](https://codesandbox.io/s/y0q1q281kz) to test `draft-js` editor. It has 2 editors inside separate iframes, and one in the main window.

### CODE REVIEW

**Comment by claudiopro** [comment]
I also found an issue when the iframed Editor has a `placeholder` prop, the placeholder text is rendered as a text block and the caret is placed on the next line.

Repro: https://codesandbox.io/s/nk90w2jv9j

**Comment by claudiopro** [comment]
@haikyuu do you need any help to address the review feedback? I'd like to merge this since it's in a good shape and there are many interested consumers!

**Comment by claudiopro** [comment]
Hi @haikyuu, would you have time to look into the finishing touch to this PR?

Several Draft.js users who are eager to embed editors in an iframe would be thankful for your efforts 😄

**Comment by marek-baranowski** [comment]
Hey @haikyuu, I'm also blocked by the iframe issue and I would love to see this PR merged :)

**Comment by haikyuu** [comment]
@marek-baranowski @claudiopro continued the work on #1938 👍

**Comment by niveditc** [comment]
Closing this since it's continued on #1938 instead.

**Pull request closed without merging**
