### PR TITLE
Add check for selection type of None

### PR DESCRIPTION
**Pull request by dirkholsopple**
This fixes https://github.com/facebook/draft-js/issues/1188 which occurs when attempting to extend a Selection with type 'None'

### CODE REVIEW

**Comment by mshibl** [comment]
I just tested this locally and it works as expected

**Comment by Cplantijn** [comment]
Thanks for the fix, @dirkholsopple! Hope this gets merged in soon.

**Comment by andrewhl** [comment]
+1 I would also like to see this merged in.

**Comment by juliankrispel** [comment]
Ya it'd be great to get this fixed!

**Comment by gdehmlow** [comment]
Please please please merge this

**Comment by andrewhl** [comment]
@dirkholsopple Hi. Can you resolve the conflict with master? I'm very eager to get this PR merged in 😁

**Comment by spicyj** [comment]
Closing in favor of #1190.

**Pull request closed without merging**
