### PR TITLE
Fix video component style issues in media example

### PR DESCRIPTION
**Pull request by jackyho112**
# Summary

Fix two style issues on the `video` component in the media example on Firefox and maybe Safari(I could not reproduce it there) by setting its `white-space` css property to 'initial' from 'pre-wrap' inherited from the `.public-DraftEditor-content` div's inline styles. 

For more information on the style issues, see https://github.com/facebook/draft-js/issues/1310. 

# Test Plan

Open `media.html` in the `media` folder in Safari and Firefox and check if the above-mentioned issues still appear.

Let me know if there is anything else I can improve on this PR. Thanks!

### CODE REVIEW

**Comment by aadsm** [comment]
@jackyho112, I've noticed you deleted your branch and closed this PR, was it for any specific reason? I'm not able to repro with the latest versions of Firefox and Safari (on Mac).

**Comment by jackyho112** [comment]
@aadsm 

I closed it to test it more, but then I forgot about it. Anyway, it is reopened now.

**Comment by jackyho112** [comment]
@flarnie 

Let me know if there is any improvement you have in mind on the branch.

**Comment by jackyho112** [comment]
Flow and lint checks are failing. Should I fix them in this branch?

**Comment by aadsm** [comment]
@jackyho112, if they pass locally it should be fine, @flarnie is fixing ci here: https://github.com/facebook/draft-js/pull/1349

PS: sorry for the delay answering, somehow I missed your comment.

**Comment by jackyho112** [comment]
@aadsm 

No worries. The steps to reproduce the issue are

1. Open `draft-js/examples/draft-0-10-0/media/media.html` in your Firefox browser
2. Click `Add Video` and type `media.mp4`
3. Click `Confirm`
4. You should get
screen shot 2017-08-30 at 4 10 53 pm

That's what I got. I couldn't reproduce it on Chrome or Safari though.

**Comment by aadsm** [comment]
Gotcha, this looks like a Firefox bug though :). Happy to accept this PR!
Yeah, I took some time to help a bit, thank you!

**Comment by jackyho112** [comment]
@aadsm Added!

**Comment by flarnie** [comment]
Just added this to a list of PRs to merge after we fix CI by landing https://github.com/facebook/draft-js/pull/1349

Thanks for your patience~ ⏳🙏✨

**Comment by jackyho112** [comment]
@flarnie 

All good! Look forward to it getting merged!

**Pull request closed without merging**
