### PR TITLE
Fix some CSS classnames

### PR DESCRIPTION
**Pull request by jerrysu**
I was just looking through the codez.

### CODE REVIEW

**Comment by tuilamap17** [comment]
1

**Comment by hellendag** [comment]
@jerrysu in the house!

**Comment by timmfin** [comment]
I know this is already merged, but if you really wanted to keep slashes in CSS you could escape them:

```scss
// This a an error in LibSass, "invalid top-level expression on line 2 at column 1" (tested via www.sassmeister.com)
.DraftEditor-alignLeft .public-DraftEditorPlaceholder/root {
  left: 0;
  text-align: left;
}

// But escaping the slash works (via http://stackoverflow.com/questions/18485059/forward-slash-in-class-name)
.DraftEditor-alignLeft .public-DraftEditorPlaceholder\/root {
  left: 0;
  text-align: left;
}
```

**Comment by zpao** [comment]
The slashes have meaning internally and get transformed away so we won't do the escaping, but that's good to know :)

**Pull request merged**
