### PR TITLE
Bumps underscore.string to 3.3.5

### PR DESCRIPTION
**Pull request by claudiopro**
**Summary**

Updates [underscore.string](https://www.npmjs.com/package/underscore.string) to v3.3.5 to mitigate ReDoS vulnerability tracked by https://github.com/epeli/underscore.string/issues/510

**Test Plan**

```sh
cd website
yarn
yarn start
```

### CODE REVIEW

**Comment by yangshun** [comment]
I just tried this same approach in Docusaurus 1 core but `underscore.string@2.4.0` still remains.

```
=> Found "remarkable#underscore.string@2.4.0"
info Reasons this module exists
   - "_project_#docusaurus#remarkable#argparse" depends on it
   - Hoisted from "_project_#docusaurus#remarkable#argparse#underscore.string"
info Disk size without dependencies: "76KB"
info Disk size with unique dependencies: "76KB"
info Disk size with transitive dependencies: "76KB"
info Number of shared dependencies: 0
```

I'm not sure if explicitly bumping `underscore.string` will help at all. `remarkable` depends on a very old (pre 1.0.0) version of `argparse` (`argparse": "~0.1.15"` in its `package.json`) and we can't get rid of `underscore.string` unless `remarkable` upgrades.

**Comment by JoelMarcey** [comment]
Is that an issue we can file at https://github.com/jonschlinkert/remarkable re: upgrading?

**Comment by claudiopro** [comment]
@JoelMarcey we should, but the fact that [a PR to fix a ReDoS vulnerability](https://github.com/jonschlinkert/remarkable/pull/334) has not been responded for two months doesn't give me much hope

I tried to DM Jon on Twitter but he hasn't replied yet 😞

**Comment by claudiopro** [comment]
This is addressed by https://github.com/jonschlinkert/remarkable/issues/310

**Comment by yangshun** [comment]
@claudiopro I think we can close this issue now that we've moved the website to Docusaurus 2

**Pull request closed without merging**
