### PR TITLE
Right and Left Arrow Event Handling

### PR DESCRIPTION
**Pull request by eessex**
Exposes right and left keyboard events, as suggested in [this issue](https://github.com/facebook/draft-js/issues/219) by @hellendag.

This will greatly simplify some of our arrow handling at [Artsy](https://github.com/artsy/positron/blob/master/client/apps/edit/components/content2/sections/text/index.coffee#L121).

The test suite is passing locally.

### CODE REVIEW

**Comment by eessex** [comment]
This build was not able to complete, but the tests are passing locally.  Is it possible to trigger a rebuild?

**Comment by flarnie** [comment]
Hi @eessex! Thanks for adding this.

I just triggered a rebuild, and in general you can also trigger a rebuild by rebasing your branch on master and force pushing your branch. Looks like tests were just failing spuriously, probably due to some issue with CI itself.

I think this looks good and makes sense. I'm trying to manually test it and when I manually added an `onLeftArrow` prop to the `rich` example, with a callback, the callback wasn't being called.

Going to debug this a little more and see if I can figure out what I'm missing.

**Comment by eessex** [comment]
Thanks @flarnie! I'll try some manual debugging on my side as well

**Comment by flarnie** [comment]
Maybe I forgot to re-run `yarn build` or something - it works for me now. Thanks!

happy_golden_retriever

Adding this to the queue for merging.

**Pull request closed without merging**
