### PR TITLE
Migrate to Docusaurus

### PR DESCRIPTION
**Pull request by aadsm**
This PR updates the website to https://github.com/facebook/docusaurus.

This changes the styling of the website from what we have today in https://draftjs.org/ to the default docusaurus styling for documentation. As of today it's not easy to customize the styling of the documentation, the only way would be to override all selectors and be at the mercy of any docusaurus future styling changes.
The main page is still pretty much the same but with an additional footer.

You can check it out here: https://aadsm.github.io/draft-js/

aadsm github io_draft-js_

aadsm github io_draft-js_docs_getting-started html

### CODE REVIEW

**Comment by flarnie** [comment]
Exciting!

@Daniel15 you did the set-up for our current site to get published to draftjs.org, any idea how well this will mesh with the current set-up?

**Comment by Daniel15** [comment]
It should work fine as long as GitHub Pages works with the changes. Seems fine to me 👍 . The Travis build is failing (https://travis-ci.org/facebook/draft-js/builds/326684734) so you'll need to update that too.

I wonder if it's worth migrating the site to Netlify at the same time to simply the deployment process a bit (as the built files wouldn't have to be committed to source control like they do with GitHub Pages). @aadsm would you like to experiment with using Netlify for the build? Totally optional but it'd add some useful functionality (like a deployment process that's easier to maintain, and preview links for pull requests).

**Comment by aadsm** [comment]
Oh, for some reason I didn't get notifications about these comments :(.
@Daniel15, What do you mean with migrating the site to Netlify? Docusaurus should be able to do everything we need, it also includes a script to publish to gh-pages. Not sure about the preview links though, let me check the Netlify project first :P

**Comment by Daniel15** [comment]
> Docusaurus should be able to do everything we need, it also includes a script to publish to gh-pages.

@aadsm - Netlify is a hosting service. We wouldn't need a script to publish to gh-pages if we used it, as it allows a custom build process to be specified, which they run as part of the deployment. Publishing to gh-pages is an ugly hack around GitHub Pages' limitations.

**Comment by Daniel15** [comment]
> Docusaurus should be able to do everything we need, it also includes a script to publish to gh-pages.

@aadsm - Netlify is a hosting service. We wouldn't need a script to publish to gh-pages if we used it, as it allows a custom build process to be specified, which they run as part of the deployment. Publishing to gh-pages is an ugly hack around GitHub Pages' limitations.

The React, Yarn and Babel sites all use Netlify.

**Comment by ericnakagawa** [comment]
A team member at Netlify is in the process of adding instructions for how to publish Docusaurus sites to Netlify!

**Comment by flarnie** [comment]
Hi! I'm starting to look at how Jest does their integration of Docusaurus with CI, hope I can help with that part.

https://github.com/facebook/jest/tree/master/website

For now going to add a couple of minor things.

**Comment by flarnie** [comment]
Once we get things hooked up we could consider sharing tips on integrating with Travis in the Docusuarus docs - https://github.com/facebook/Docusaurus/issues/423

**Comment by flarnie** [comment]
I might have time to help wrap this up over the weekend - any ideas about how I can help? Mainly was going to try and get CI passing.

**Comment by flarnie** [comment]
I'm merging a PR which adds a favicon, will update this branch to also use the favicon when I get a chance. 
https://github.com/facebook/draft-js/pull/1526

**Comment by flarnie** [comment]
Thanks @yangshun - I think @NoamELB was also looking at this PR and had some notes on what needs done to get it mergable.

When it's passing CI, if that's possible (?), we just need some folks to be on deck to help in case the site goes down when it lands. But I'm hoping it will *just work*.

@JoelMarcey may also be able to help.

**Comment by NoamELB** [comment]
Hi @yangshun, check out the fork I did for this pull request https://github.com/NoamELB/draft-js/tree/docusaurus (up to date with the latest master).
I fixed a few problems like Google Analytics code and non-working footer links.

There are two problem left:
1. 'tab' input inside the Draft.js editor not working. Instead of applying a style (for example on a ul/ol list item), they are moving the focus to the "Learn more about Draft" button.

2. (minor issue with the layout) The landing page is quite short so in large screens the footer will not stick to the bottom, while leaving an empty white blank below it. We may be using it wrong or it's an issue with Docusaurus. If it is an issue - I can open a pull request to fix it (it's like 4 lines of css on the "navPusher" class).

Anyway, it will be amazing if you can help with either 😇

**Comment by JoelMarcey** [comment]
@NoamELB Hi Noam - for your #2 issue, yesterday we merged https://github.com/facebook/Docusaurus/pull/637. Would that solve your problem?

**Comment by yangshun** [comment]
@NoamELB Problem 2 should be fixed after facebook/Docusaurus#637 as @JoelMarcey mentioned. I'll look into problem 1 tonight 😄

**Comment by yangshun** [comment]
@NoamELB I looked into the problem. It seems to be an outdated DraftJS issue. draftjs.org is using v0.10.5 but your branch is loading v0.10.4. Upgrading to v0.10.5 seems to fix the problem for me. 

Also, we released Docusaurus 1.0.15 yesterday, you might want to upgrade to 1.0.15 in your branch.

**Comment by NoamELB** [comment]
@yangshun @JoelMarcey Good catch with v0.10.4, it fixed that. Now I'm trying to understand why the new version is not generated automatically... For some reason the dist files are hardcoded in the website folder.

Docusaurus 1.0.15 looks better, but I think it is just missing a `justify-content: space-between;` on .navPusher (https://i.imgur.com/t576ouN.png). Maybe the footer should be directly under `body`?

**Comment by yangshun** [comment]
@NoamELB You're right. Our sticky footer fix was half-baked - it only works on the docs page. I'll come up with a fix for it soon enough. Could we try to migrate first? I think the footer fix is not as important at the moment considering you need to have a really tall monitor to reproduce that. Hopefully we'll roll out a proper footer fix in 1.0.16.

**Comment by niveditc** [comment]
Hey folks! I'm not too familiar with our Docusaurus efforts, so would love some more context on the current state of this PR. Based on the commits by @NoamELB & @yangshun, I believe that we're now using Docusaurus! Is there still something that needs to be merged from this PR or can we close it? :)

**Comment by Daniel15** [comment]
Yeah, #1759 was a continuation of this PR. Now that it's merged, we can close this one. Thank you to everyone that contributed 😃

**Pull request closed without merging**
