### PR TITLE
Remove extra spaces from the text decoration style

### PR DESCRIPTION
**Pull request by llh1**
Fix IE issue raised in #377

### CODE REVIEW

**Comment by spicyj** [comment]
Can you add a comment noting which versions of IE this is necessary for? Just something as simple as:

```
// .trim() is necessary for IE10
```

Do you know if it's a problem in latest Edge too?

**Comment by llh1** [comment]
Okay done. I've tested it with IE9, IE10, IE11 and Edge so far (using the emulation tool in IE11).

**Comment by hellendag** [comment]
Weird.

**Comment by hellendag** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-3** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1719029811707434/int_phab) to review.

**Pull request closed without merging**
