### PR TITLE
Prevent clobbering inline style overrides if the selection position is the same

### PR DESCRIPTION
**Pull request by tjaneczko**
This PR is meant to address #696 and to mitigate some of the issues of #726 .  The issue stems from the fact that `updateSelection` will automatically clear the `inlineStyleOverride` whenever it's called.  `updateSelection` is called both on blur and on focus of the editor (and in various other places), which causes any button presses for setting an inline style to completely clear the inline style overrides.  This PR checks to see if the position of the selection changes and will not clear the `inlineStyleOverride` if the positions have not changed.

Please let me know if this needs any adjustment or if more tests should be added to check for this functionality.

### CODE REVIEW

**Comment by denich** [comment]
Would be nice to have this PR merged, are there any plans to do it?

**Comment by koutsenko** [comment]
Any updates?

**Comment by tjaneczko** [comment]
Sure thing!  I think when I initially wrote this PR draft.js was still using `var`, but I'll switch over to `const`, clean things up a bit, and add test cases.  Thanks for the review!

**Comment by niveditc** [comment]
@tjaneczko - just wanted to ping this PR! We'd be happy to merge it in once you've gotten a chance to make the changes :)

**Comment by tjaneczko** [comment]
Unfortunately, I've been incredibly busy since I last posted on this PR, so I haven't had a chance to get those changes in yet.  I'll definitely look at trying to get them in soon, hopefully sometime this week!

**Comment by rahul1995** [comment]
@tjaneczko Why is this PR closed without merging?

**Comment by tjaneczko** [comment]
@rahul1995 I unfortunately haven't had time to work on this in a long time (and I'm no longer working on anything directly using draft-js), and it seems like #2092 may fix this.  If not, someone else is more than welcome to pick this up again

**Comment by rahul1995** [comment]
@tjaneczko could you please reopen this PR? I still don't understand why this one was closed.

**Comment by Davidkle** [comment]
A good work around is discussed in [#969 
](https://github.com/facebook/draft-js/issues/696#issuecomment-427575609).

The work around is to force the editor to be in focus before applying the style.

**Pull request closed without merging**
