### PR TITLE
Move immutable to peerDependencies

### LINKED ISSUE #1237: Package "immutable" should be placed in "peerDependencies".

### PR DESCRIPTION
**Pull request by arshadkazmi42**
*Before* submitting a pull request, please make sure the following is done...

1. Fork the repo and create your branch from `master`.
2. If you've added code that should be tested, add tests!
3. If you've changed APIs, update the documentation.
4. Ensure that:
  * The test suite passes (`npm test`)
  * Your code lints (`npm run lint`) and passes Flow (`npm run flow`)
  * You have followed the [testing guidelines](https://github.com/facebook/draft-js/wiki/Testing-for-Pull-Requests)
5. If you haven't already, complete the [CLA](https://code.facebook.com/cla).

Please use the simple form below as a guideline for describing your pull request.

Thanks for contributing to Draft.js!

-

**Summary**

Move `"immutable": "~3.7.4"` from `dependencies` to `peerDependencies` in `package.json`

Closes #1237

**Test Plan**

NA

### CODE REVIEW

**Comment by TrySound** [comment]
Should it be? What if I use another package with older immutable version? My app will be completely broken and I won't be able to fix it.

What problem are you trying to solve here? It's not clear from the issue.

**Comment by arshadkazmi42** [comment]
@TrySound it was reported issue so I made the changes, it this change not required?

@niveditc I will make the changes and update my commit

**Comment by arshadkazmi42** [comment]
@niveditc I am getting this error on running `yarn`

`const missingModule = e.toString().match(EXTRACT_MODULE_NAME_REGEX)[1];
                                                                           ^

TypeError: Cannot read property '1' of null
    at files.forEach (/Users/arshad/Arshad/workspace/opensource/hacktoberfest/draft-js/node_modules/fbjs-scripts/node/check-lib-requires.js:30:76)
    at Array.forEach (<anonymous>)
    at fs.readdir (/Users/arshad/Arshad/workspace/opensource/hacktoberfest/draft-js/node_modules/fbjs-scripts/node/check-lib-requires.js:22:9)
    at FSReqWrap.oncomplete (fs.js:135:15)`

**Comment by niveditc** [comment]
Thanks for commenting on #1237 - let's wait to see if this change is needed, since I don't have much context.

**Comment by niveditc** [comment]
Closing since we weren't able to come up with rationale for this change. Apologies for the mislabeled issue!

**Pull request closed without merging**
