### PR TITLE
Fixed applying entities across multiple blocks

### PR DESCRIPTION
**Pull request by johanneslumpe**
Fixes https://github.com/facebook/draft-js/issues/349

### CODE REVIEW

**Comment by hellendag** [comment]
Thank you!

**Comment by hellendag** [comment]
@facebook-github-bot import

**Comment by johanneslumpe** [comment]
👍

**Comment by facebook-github-bot-2** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1134400023269036/int_phab) to review.

**Pull request closed without merging**
