### PR TITLE
fix automatically scroll when the new line in the list block type

### PR DESCRIPTION
**Pull request by sugarshin**
ref: https://github.com/facebook/draft-js/issues/320

### CODE REVIEW

**Comment by hellendag** [comment]
This seems okay, but it would be helpful to have more information on the change. Can you provide a video of the bug in action, and some details on how you tested this change? Thanks!

**Comment by mitermayer** [comment]
Hi @sugarshin , it looks like this pull request has been abandoned, so I am going to close it. If someone is still interested in working on this please feel free to reopen it!

**Comment by rahul1995** [comment]
@mitermayer Any updates? This is still a bug even after 1.5 years

**Comment by lomeat** [comment]
@mitermayer This bug existing in editor for 3.5 years as I see. So you can't write large texts in small windows. Its not comfortable.

**Pull request closed without merging**
