### PR TITLE
Add syntax highlighting to API Basics documentation

### PR DESCRIPTION
**Pull request by wyze**
This can be done to quite a few more documents. Should I do separate PRs for each or can I group as one larger syntax highlighting addition PR?

### CODE REVIEW

**Comment by zpao** [comment]
Thanks! We can do it all as 1 PR.

**Comment by wyze** [comment]
Okay @zpao. I will make changes, rebase and squash it.

**Comment by wyze** [comment]
Should be good to go now!

**Comment by zpao** [comment]
Thanks! I'll merge this now and if you have any others, feel free to open another PR.

**Pull request merged**
