### PR TITLE
Update Flow comment supression regex

### PR DESCRIPTION
**Pull request by zpao**
**Summary**

I'm not sure why we need to change this. The magic bit seems to be needing to match the newline, the rest of the changes just bring use more in line with the internal flowconfig. Maybe @jeffmo can tell us why?

**Test Plan**

`npm run flow`

### CODE REVIEW

**Comment by spicyj** [comment]
Maybe without the newline, the comment needs to be on the same line as the offending code?

**Comment by zpao** [comment]
Seems to work fine internally without the newline. ¯\_(ツ)_/¯

**Comment by jeffmo** [comment]
Pretty weird... I'm not sure what would've changed here :/

**Comment by zpao** [comment]
Going to land this since it gets us back to green. We can revisit how we want that suppression to look and try to figure out the issue later.

**Pull request merged**
