### PR TITLE
Upgrade Jest

### PR DESCRIPTION
**Pull request by zpao**
Might as well.

### CODE REVIEW

**Comment by spicyj** [comment]
k

**Comment by zpao** [comment]
@facebook-github-bot-5 shipit

**Comment by spicyj** [comment]
@facebook-github-bot shipit

**Comment by facebook-github-bot-0** [comment]
Thanks for importing. If you are an FB employee go to [Phabricator](https://our.intern.facebook.com/intern/opensource/github/pull_request/1030963906990876/int_phab) to review.

**Pull request closed without merging**
